//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace platform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kullanicilar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public kullanicilar()
        {
            this.paylasimlars = new HashSet<paylasimlar>();
        }
    
        public int id { get; set; }
        public string kullaniciAD { get; set; }
        public string kullaniciParola { get; set; }
        public string Eposta { get; set; }
        public Nullable<System.DateTime> kayitTarihi { get; set; }
        public Nullable<int> yetkiID { get; set; }
        public string kullaniciSlogan { get; set; }
        public string resimYolu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<paylasimlar> paylasimlars { get; set; }
        public virtual yetki yetki { get; set; }
    }
}
