//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace platform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class paylasimlar
    {
        public int id { get; set; }
        public string paylasimBaslik { get; set; }
        public string paylasimMetin { get; set; }
        public Nullable<int> kullaniciID { get; set; }
        public Nullable<int> konuID { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public Nullable<int> begeniSayisi { get; set; }
    
        public virtual konular konular { get; set; }
        public virtual kullanicilar kullanicilar { get; set; }
    }
}
