//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace platform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class platform
    {
        public int id { get; set; }
        public string platformAdi { get; set; }
        public string hakkinda { get; set; }
        public string slogan { get; set; }
    }
}
